### ISSUE TITLE
Python script for Vascan-Editor missing

### ISSUE THREAD

**Issue by cgendreau** [Canadensys/canadensys-ansible#3]
Vascan-Editor usually sets up a cron job that will call a script to start the process of 'compiling Vascan'.
Originally, the script was a php file but it could be simplified by using a Python script instead.

**Comment by JeGoi** [comment]
It is done there; https://github.com/Canadensys/canadensys-ansible/blob/master/roles/app_vascan_editor/templates/vascan_editor_cron.py.j2
but i forget to closed this issue during the commit.
